### ISSUE TITLE
Does not work on Node 10

### ISSUE THREAD

**Issue by noffle** [noffle/handshake-stream#1]
According to Travis, across {Windows,macOS,Linux}:

```
not ok 23 Error: unexpected non-ready-signal byte received
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [Error: unexpected non-ready-signal byte received]
    at: f (/Users/travis/build/noffle/handshake-stream/node_modules/once/once.js:25:25)
    stack: |-
      Error: unexpected non-ready-signal byte received
          at Writable.HandshakeStream.w._write (/Users/travis/build/noffle/handshake-stream/index.js:31:21)
          at doWrite (_stream_writable.js:415:12)
          at writeOrBuffer (_stream_writable.js:399:5)
          at Writable.write (_stream_writable.js:299:11)
          at Duplexify._write (/Users/travis/build/noffle/handshake-stream/node_modules/duplexify/index.js:208:22)
          at doWrite (/Users/travis/build/noffle/handshake-stream/node_modules/readable-stream/lib/_stream_writable.js:428:64)
          at writeOrBuffer (/Users/travis/build/noffle/handshake-stream/node_modules/readable-stream/lib/_stream_writable.js:417:5)
          at Duplexify.Writable.write (/Users/travis/build/noffle/handshake-stream/node_modules/readable-stream/lib/_stream_writable.js:334:11)
          at Duplexify.ondata (/Users/travis/build/noffle/handshake-stream/node_modules/readable-stream/lib/_stream_readable.js:619:20)
          at Duplexify.emit (events.js:198:13)
  ...
not ok 24 should be equivalent
  ---
    operator: deepEqual
    expected: |-
      [ { left: 3, sender: 'b' }, { left: 2, sender: 'b' }, { left: 1, sender: 'b' } ]
    actual: |-
      []
    at: f (/Users/travis/build/noffle/handshake-stream/node_modules/once/once.js:25:25)
  ...
not ok 25 should be equivalent
  ---
    operator: deepEqual
    expected: |-
      [ { left: 3, sender: 'a' }, { left: 2, sender: 'a' }, { left: 1, sender: 'a' } ]
    actual: |-
      []
    at: f (/Users/travis/build/noffle/handshake-stream/node_modules/once/once.js:25:25)
```

https://travis-ci.org/noffle/handshake-stream/jobs/547435256

**Comment by hackergrrl** [comment]
Fixed as of 3.0.5
